version: '3.8'
services:
  app:
    image: bharath/app:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "8080:80"
    volumes:
      - /opt/kickstart-docker/app:/opt/app
      - /opt/kickstart-docker/nginx/conf/main.conf:/etc/nginx/nginx.conf
      - /opt/kickstart-docker/nginx/conf/app.conf:/etc/nginx/conf.d/app.conf
      - /opt/kickstart-docker/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/supervisor/conf/app.ini:/etc/supervisord.d/app.ini
      - /opt/kickstart-docker/supervisor/conf/nginx.ini:/etc/supervisord.d/nginx.ini
    depends_on:
      - redis
    networks:
      common:
        ipv4_address: 100.1.1.10
  redis:
    image: bharath/redis:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    volumes:
      - redis-data:/opt/redis/data
      - redis-log:/opt/redis/log
      - /opt/kickstart-docker/redis/conf/main.conf:/opt/redis/conf/redis.conf
      - /opt/kickstart-docker/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/supervisor/conf/redis.ini:/etc/supervisord.d/redis.ini
    networks:
      common:
        ipv4_address: 100.1.1.20
volumes:
  redis-data:
    driver: local
  redis-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.1.0.0/16
